//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.App.Domain {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Entities {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entities() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.App.Domain.Entities", typeof(Entities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MeasurementTypeId {
            get {
                return ResourceManager.GetString("MeasurementTypeId", resourceCulture);
            }
        }
        
        public static string MeasurementType {
            get {
                return ResourceManager.GetString("MeasurementType", resourceCulture);
            }
        }
        
        public static string ValueUnitId {
            get {
                return ResourceManager.GetString("ValueUnitId", resourceCulture);
            }
        }
        
        public static string ValueUnit {
            get {
                return ResourceManager.GetString("ValueUnit", resourceCulture);
            }
        }
        
        public static string ReachedAt {
            get {
                return ResourceManager.GetString("ReachedAt", resourceCulture);
            }
        }
        
        public static string ExerciseTypeId {
            get {
                return ResourceManager.GetString("ExerciseTypeId", resourceCulture);
            }
        }
        
        public static string ExerciseType {
            get {
                return ResourceManager.GetString("ExerciseType", resourceCulture);
            }
        }
        
        public static string CountryId {
            get {
                return ResourceManager.GetString("CountryId", resourceCulture);
            }
        }
        
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        public static string Leaderboard {
            get {
                return ResourceManager.GetString("Leaderboard", resourceCulture);
            }
        }
        
        public static string LeaderboardId {
            get {
                return ResourceManager.GetString("LeaderboardId", resourceCulture);
            }
        }
        
        public static string PerformedAt {
            get {
                return ResourceManager.GetString("PerformedAt", resourceCulture);
            }
        }
        
        public static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        public static string ExerciseId {
            get {
                return ResourceManager.GetString("ExerciseId", resourceCulture);
            }
        }
        
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        public static string DurationUnit {
            get {
                return ResourceManager.GetString("DurationUnit", resourceCulture);
            }
        }
        
        public static string DurationUnitId {
            get {
                return ResourceManager.GetString("DurationUnitId", resourceCulture);
            }
        }
        
        public static string ProgramId {
            get {
                return ResourceManager.GetString("ProgramId", resourceCulture);
            }
        }
        
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        public static string IsCreator {
            get {
                return ResourceManager.GetString("IsCreator", resourceCulture);
            }
        }
        
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        public static string SessionId {
            get {
                return ResourceManager.GetString("SessionId", resourceCulture);
            }
        }
        
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        public static string PerformanceId {
            get {
                return ResourceManager.GetString("PerformanceId", resourceCulture);
            }
        }
        
        public static string QuantityUnit {
            get {
                return ResourceManager.GetString("QuantityUnit", resourceCulture);
            }
        }
        
        public static string QuantityUnitId {
            get {
                return ResourceManager.GetString("QuantityUnitId", resourceCulture);
            }
        }
        
        public static string WeightUnit {
            get {
                return ResourceManager.GetString("WeightUnit", resourceCulture);
            }
        }
        
        public static string WeightUnitId {
            get {
                return ResourceManager.GetString("WeightUnitId", resourceCulture);
            }
        }
        
        public static string Reps {
            get {
                return ResourceManager.GetString("Reps", resourceCulture);
            }
        }
        
        public static string Sets {
            get {
                return ResourceManager.GetString("Sets", resourceCulture);
            }
        }
        
        public static string UserExercise {
            get {
                return ResourceManager.GetString("UserExercise", resourceCulture);
            }
        }
        
        public static string UserExerciseId {
            get {
                return ResourceManager.GetString("UserExerciseId", resourceCulture);
            }
        }
        
        public static string SessionExercise {
            get {
                return ResourceManager.GetString("SessionExercise", resourceCulture);
            }
        }
        
        public static string SessionExerciseId {
            get {
                return ResourceManager.GetString("SessionExerciseId", resourceCulture);
            }
        }
    }
}
